title: Stat Arxiv of Today
author: Daniele Zago
email: 
url: https://dedzago.github.io
baseurl: /arxiv_rss
description: > # description of the site (multiple lines allowed)
feed:
  posts_limit: 500
permalink: 

favicon: 
remote-theme: no-style-please 

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
