name: Update Website

on:
  schedule:
    - cron: '*/10 * * * *' # test deploy
      #- cron: '0 9 * * *' 

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest  # Replace with desired runner OS (if needed)
    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Use Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Adjust if needed

      - name: Run update script
        run: python rss_arxiv.py

      - name: Run deploy script
        run: ./bin/deploy.sh
