name: Deploy Jekyll Website

on:
  push:
    branches: [ static ]
  schedule:
    - cron: "0 7 * * 1-5"  # Runs at 7:00 (UTC) = 9 rome on weekdays

  workflow_dispatch:

jobs:
  update_content:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4  #  Cambia branch
        with:
          ref: main  # change branch if on another
          persist-credentials: true # E lascialo per tutto

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: update rss # Aggiorna sito con python
        run: |
          python -m pip install -r requirements.txt
          python rss_arxiv.py

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Build Jekyll site 
        run: bundle exec jekyll build  

      - name: Deploy to GitHub Pages  # Deploy tramite secret creato da impostazioni generali
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.JK_TOKEN }}
          publish_dir: ./_site 

