name: Update Website Daily

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every day at 9:00 AM (adjust as needed)
  workflow_dispatch:

jobs:

  update_content:
    runs-on: ubuntu-latest  # Replace with desired runner OS (if needed)
    steps:
      - uses: actions/checkout@v3  # Checkout code (within this job too)
        with:
          ref: static

      - name: Use Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Adjust if needed

      - name: get requirements
        run: |
          python -m pip install -r requirements.txt
          python rss_arxiv.py

  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: static
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
